# -*- coding: utf-8 -*-
"""segment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bt1D5GRG2FbAnd41xGO7hBe0KwtIDaeX
"""

import py_vncorenlp
from tqdm import tqdm

# Automatically download VnCoreNLP components from the original repository
# and save them in some local machine folder
py_vncorenlp.download_model(save_dir='/absolute/path/to/vncorenlp')

# Load the word and sentence segmentation component
rdrsegmenter = py_vncorenlp.VnCoreNLP(annotators=["wseg"], save_dir='/absolute/path/to/vncorenlp')

# Define input and output file paths
input_file_path = '/content/output.txt'
output_file_path = '/content/output_segmented.txt'

# Read the content of the input file
with open(input_file_path, 'r', encoding='utf-8') as file:
    text = file.read()

# Segment the text using VnCoreNLP with tqdm progress bar
segmented_text = []
with tqdm(total=len(text.split('\n')), desc="Segmenting") as pbar:
    for line in text.split('\n'):
        segmented_line = rdrsegmenter.word_segment(line)
        segmented_text.append(segmented_line)
        pbar.update(1)

# Write the segmented content to the output file
with open(output_file_path, 'w', encoding='utf-8') as file:
    for line in segmented_text:
        for sentence in line:
            file.write(sentence + '\n')

print("Segmentation completed. Segmented text saved to", output_file_path)